name: collective_rewiring
channels:
  - conda-forge
  - defaults
dependencies:
  # Core packages available via conda
  - python=3.11  # Using 3.11 for better compatibility
  - numpy=1.24.2
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - networkx
  - imageio
  - rustworkx
  - setuptools
  - wheel
  - dill
  - joblib
  # Packages that need to be installed via pip
  - pip
  - pip:
    - netin
    - node2vec
    - leidenalg
    - python-igraph
    - igraph

